import { auth } from './firebase.js';
import { watchAuth, logout } from './auth.js';
const $=id=>document.getElementById(id);let token=null,currentUser=null;
async function api(path,options={}){if(!token)token=await auth.currentUser.getIdToken(true);const headers={...(options.body instanceof FormData?{}:(options.body?{'Content-Type':'application/json'}:{})),...(options.headers||{}),Authorization:`Bearer ${token}`};const res=await fetch(path,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'Request failed.');return data;}
const fmt=d=>d?new Date(d).toLocaleString():'Never';const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function load(){try{const data=await api('/api/auth/me');currentUser=data.user;$('welcome').textContent=`Welcome, ${data.user.name||'Vault user'}`;$('emailText').textContent=data.user.email||data.user.whatsappNumber||'';const vip=data.user.vip?.active===true;$('accessBadge').textContent=vip?`💎 ${data.user.vip.plan}`:(data.user.trial?.active?'⏳ FREE 24H TRIAL':'🔒 TRIAL EXPIRED');$('trialStatus').textContent=data.user.trial?.active?'ACTIVE':'EXPIRED';$('trialExpiry').textContent=data.user.trial?.expiresAt?`Ends: ${fmt(data.user.trial.expiresAt)}`:'';$('vipStatus').textContent=vip?data.user.vip.plan:'NONE';$('vipExpiry').textContent=vip&&data.user.vip.plan!=='LIFETIME'?`Until: ${fmt(data.user.vip.expiresAt)}`:(vip?'Lifetime access':'');$('refCount').textContent=data.user.referral?.qualifiedCount??0;$('refLink').value=`${location.origin}/signup.html?ref=${encodeURIComponent(data.user.referral?.code||data.user.refCode||'')}`;if(data.isAdmin===true||data.user.role==='ADMIN')$('adminLink').classList.remove('hidden');if(data.user.whatsappNumber)$('botPhone').value=data.user.whatsappNumber;await Promise.all([loadBotStatus(),loadNotifications(),loadTutorials(),loadMethods()]);maybeShowOfficialPopup(data.user);}catch(e){$('welcome').textContent=e.message;}}
async function loadBotStatus(){try{const d=await api('/api/bot/status');$('botStatus').textContent=d.connected?'🟢 Connected':(d.trial?.active?'🆓 24H Trial Ready':'🔴 Not connected');}catch{$('botStatus').textContent='Unavailable';}}
$('pairBtn').onclick=async()=>{const phone=$('botPhone').value.trim();$('botMessage').textContent='Generating real pairing code…';$('pairResult').classList.add('hidden');try{const d=await api('/api/bot/pair',{method:'POST',body:JSON.stringify({whatsappNumber:phone})});$('pairCode').textContent=d.pairingCode;$('pairInstructions').innerHTML=(d.instructions||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('trialNotice').textContent=d.vip?.active?`💎 VIP access: ${d.vip.plan}.`:'🆓 You are using the FREE 24-HOUR TRIAL. Your trial begins when the bot connects.';$('pairResult').classList.remove('hidden');$('botMessage').textContent=d.message;await loadBotStatus();}catch(e){$('botMessage').textContent=e.message;}};
$('disconnectBtn').onclick=async()=>{try{const d=await api('/api/bot/disconnect',{method:'POST'});$('botMessage').textContent=d.message;await loadBotStatus();}catch(e){$('botMessage').textContent=e.message;}};
async function loadMethods(){try{const d=await api('/api/payment/methods');const plan=$('planSelect').value;$('manualInstructions').innerHTML=`<strong>Manual payment instructions</strong><ol>${d.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;showManualInfo();}catch{}}
function showManualInfo(){const method=$('methodSelect').value;if(method==='PAYSTACK'){$('manualInstructions').classList.add('hidden');return;}const map={OPAY:['OPay','Timothy','9024594961'],PALMPAY:['PalmPay','Timothy','2917796858'],BINANCE:['Binance','UID: 948905475'],BYBIT:['Bybit','UID: 232942065']};const x=map[method];$('manualInstructions').innerHTML=`<strong>${x[0]}</strong><p>Account name: <b>${x[1]}</b></p><p>${x[2]}</p><p>Transfer the exact plan amount, then upload your payment screenshot. Admin review is required before VIP activation.</p>`;$('manualInstructions').classList.remove('hidden');}
$('methodSelect').onchange=showManualInfo;$('planSelect').onchange=showManualInfo;
$('paymentBtn').onclick=async()=>{try{$('paymentMessage').textContent='Creating payment…';const fd=new FormData();fd.append('recipientWhatsApp',$('whatsappInput').value.trim());fd.append('plan',$('planSelect').value);fd.append('paymentType',$('methodSelect').value==='PAYSTACK'?'PAYSTACK':'MANUAL');fd.append('method',$('methodSelect').value);if($('proofInput').files[0])fd.append('proof',$('proofInput').files[0]);const d=await api('/api/payment/create',{method:'POST',body:fd});$('paymentMessage').textContent=d.message;if(d.authorization_url)location.href=d.authorization_url;}catch(e){$('paymentMessage').textContent=e.message;}};
$('copyRef').onclick=async()=>{try{await navigator.clipboard.writeText($('refLink').value);$('copyRef').textContent='Copied';setTimeout(()=>$('copyRef').textContent='Copy',1200);}catch{}};
$('redeemBtn').onclick=async()=>{try{const d=await api('/api/coupon/redeem',{method:'POST',body:JSON.stringify({code:$('couponCode').value.trim()})});$('couponMessage').textContent=d.message;$('couponCode').value='';await load();}catch(e){$('couponMessage').textContent=e.message;}};
async function loadNotifications(){try{const d=await api('/api/notification/my');$('unread').textContent=d.unreadCount??0;$('notifications').innerHTML=d.notifications?.length?d.notifications.map(n=>`<article class="notification ${n.read?'':'unread'}"><strong>${esc(n.title)}</strong><p>${esc(n.message)}</p><small>${fmt(n.createdAt)}</small></article>`).join(''):'<p class="muted">No notifications yet.</p>';}catch{$('notifications').innerHTML='<p class="muted">Notifications unavailable.</p>';}}
async function loadTutorials(){try{const d=await fetch('/api/tutorials').then(r=>r.json());$('tutorials').innerHTML=d.tutorials?.length?d.tutorials.map(t=>`<article class="tutorial-card"><div class="tutorial-video-wrap"><video controls preload="metadata" src="${esc(t.videoUrl)}"></video></div><div class="tutorial-body"><h3>${esc(t.title)}</h3><p class="muted">${esc(t.description)}</p></div></article>`).join(''):'<p class="muted">Tutorials coming soon.</p>';}catch{$('tutorials').innerHTML='<p class="muted">Tutorials unavailable.</p>';}}
function shouldShowOfficialPopup(u){const last=u?.officialPlatformsPopupAt?new Date(u.officialPlatformsPopupAt).getTime():0;return !last||Date.now()-last>=86400000;}function maybeShowOfficialPopup(u){if(!shouldShowOfficialPopup(u))return;$('officialPopup').classList.remove('hidden');document.body.classList.add('modal-open');}async function closePopup(){ $('officialPopup').classList.add('hidden');document.body.classList.remove('modal-open');try{await api('/api/auth/official-popup-seen',{method:'PATCH'});}catch{}}
$('closeOfficialPopup').onclick=closePopup;$('maybeLaterBtn').onclick=closePopup;$('followNowBtn').onclick=async()=>{window.open('https://www.facebook.com/48HRSvault','_blank','noopener');window.open('https://www.tiktok.com/@mrmuse124?_r=1&_t=ZS-98ocL9BEV4y','_blank','noopener');window.open('https://x.com/DabereTimo14522','_blank','noopener');await closePopup();};$('logoutBtn').onclick=async()=>{await logout();location.href='/index.html'};watchAuth(u=>{if(!u)location.href='/login.html';else load();});
